### ISSUE TITLE
comparison to alternatives

### ISSUE THREAD

**Issue by jackmac92** [ema/pets#1]
chezmoi comes to mind

**Comment by ema** [comment]
Hello and thanks for your interest in pets!

Would you like to see a description of pets in comparison to chezmoi in the README? If so, please note that the "Design overview" section does touch upon the differences between pets and other configuration management systems (puppet/chef/ansible).

Please feel free to suggest whatever changes you have in mind in a PR.

**Comment by scottdotau** [comment]
> Hello and thanks for your interest in pets!
> 
> Would you like to see a description of pets in comparison to chezmoi in the README? If so, please note that the "Design overview" section does touch upon the differences between pets and other configuration management systems (puppet/chef/ansible).
> 
> Please feel free to suggest whatever changes you have in mind in a PR.

I see this as complementing chezmoi rather than be an alternative.

For example, chezmoi templates could be used to generate per-hostname/distro/etc configuration in for example `$XDG_CONFIG_HOME/pets/*`... Chezmois on change hooks can then be used to re-apply the config when the contents change.

**Comment by jackmac92** [comment]
Gotcha thanks!

I've found some ways to manage the "full configuration of the system" via chezmoi scripts, but they get pretty clunky/hacky. I think `pets` would be better suited to those!

**Comment by scottdotau** [comment]
Hey @jackmac92 i know you've closed this,

But because I was already working on something similar I can show an example of how pets can be used with chezmoi as a driver (as it's more robus in being able to template, etc)

I've just created a new repo and copied it over from my personal dotfiles on my phone, but hopefully it's small enough that you can read through and understand what it's doing so you can expand on it ☺

Hope this helps,
https://github.com/scottdotau/chezmoi-pets
